/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface VAmbulanceWlList {
    }
}
declare global {
    interface HTMLVAmbulanceWlListElement extends Components.VAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLVAmbulanceWlListElement: {
        prototype: HTMLVAmbulanceWlListElement;
        new (): HTMLVAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "v-ambulance-wl-list": HTMLVAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface VAmbulanceWlList {
    }
    interface IntrinsicElements {
        "v-ambulance-wl-list": VAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "v-ambulance-wl-list": LocalJSX.IntrinsicElements["v-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLVAmbulanceWlListElement>;
        }
    }
}
